ThemeTraining/ThemeTraining/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('samplethemes.urls')),
]

ThemeTraining/samplethemes/urls.py
from django.urls import path
from .views import CompanySignup, CompanyLogin, CompanyDetail, CompanyPeople, CompanySettings, CompanyTask, CompanyTaskDetail

app_name = 'company'

urlpatterns = [
    path('', CompanySignup.as_view(), name='company-signup'),
    path('login/', CompanyLogin.as_view(), name='company-login'),
    path('company-detail/', CompanyDetail.as_view(), name='company-detail'),
    path('company-people/', CompanyPeople.as_view(), name='company-people'),
    path('company-settings/', CompanySettings.as_view(), name='company-settings'),
    path('company-task/', CompanyTask.as_view(), name='company-task'),
    path('company-task-detail/', CompanyTaskDetail.as_view(), name='company-task-detail'),

]

ThemeTraining/samplethemes/models.py
from django.db import models

# Create your models here.

ThemeTraining/samplethemes/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


class CompanySignup(TemplateView):
    template_name = "registration/company-signup.html"

class CompanyLogin(TemplateView):
    template_name = "registration/company-login.html"

class CompanyDetail(TemplateView):
    template_name = "company_info/company-detail.html"

class CompanyPeople(TemplateView):
    template_name = "company_info/company-people.html"

class CompanySettings(TemplateView):
    template_name = "company_info/company-settings.html"

class CompanyTask(TemplateView):
    template_name = "company_info/company-task.html"

class CompanyTaskDetail(TemplateView):
    template_name = "company_info/company-task-detail.html"

ThemeTraining/templates/company_info/company-settings.html
{% extends "company_info/company-detail.html" %}
{% load static %}
	
	
	
				<!--begin::Wrapper-->
				
			
					{% block headers %}
					<ul class="header-tabs nav align-self-end font-size-lg">
						<!--begin::Item-->
						<li class="nav-item">
							<a href="{% url 'company:company-people' %}" class="nav-link py-4 px-6">People</a>
						</li>
						<!--end::Item-->
						<!--begin::Item-->
						<li class="nav-item mr-3">
							<a href="{% url 'company:company-task' %}" class="nav-link py-4 px-6">Tasks</a>
						</li>
						<!--end::Item-->
						<!--begin::Item-->
						<li class="nav-item mr-3">
							<a href="{% url 'company:company-settings' %}" class="nav-link py-4 px-6 active">Settings</a>
						</li>
						<!--end::Item-->
					</ul>
					{% endblock %}
					
					{% block content %}
					<div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">
						<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
							<!--begin::Entry-->
							<div class="d-flex flex-column-fluid">
								<!--begin::Container-->
								<div class="container">
									<div class="row">
										<div class="col-xl-12">
											<!--begin::Card-->
											<div class="card card-custom gutter-b">
												<div class="card-header">
													<div class="card-title">
														<h3 class="card-title align-items-start flex-column">
															<span class="card-label font-weight-bolder text-dark">Settings</span>
														</h3>
													</div>
												</div>
												<div class="card-body">
													<!--begin::Form-->
													<div class="row">
														<div class="col-xl-8 m-auto">														
															<form class="form mt-0" id="kt_form">
																<!--begin::User-->
																<div class="d-flex align-items-center">
																	<div class="symbol symbol-60 symbol-xxl-100 mr-5 align-self-start align-self-xxl-center">
																		<div class="symbol-label" style="background-image:url('{% static 'assets/media/users/300_13.jpg' %}')"></div>
																	</div>
																	<div>
																		<a href="#" class="font-weight-bold font-size-h5 text-dark-75 text-hover-primary">Company Name</a>
																		<div class="text-muted">Co-Founder & CTO</div>
																	</div>
																</div>
																<!--end::User-->
																<hr>
																<div class="mb-5 font-weight-bold text-dark lead">Profile Information</div>
																<div class="row">
																	<div class="col-xl-6">
																		<!--begin::Input-->
																		<div class="form-group">
																			<label>Name of the Company</label>
																			<input type="text" class="form-control form-control-lg" name="company" placeholder="Company Name" value="Cipla" />
																		</div>
																		<!--end::Input-->
																	</div>
																	<div class="col-xl-6">
																		<!--begin::Input-->
																		<div class="form-group">
																			<label>E-mail</label>
																			<input type="email" class="form-control form-control-lg" name="email" placeholder="Email Id" value="error@mail.com" />
																		</div>
																		<!--end::Input-->
																	</div>
																</div>
																<div class="row">
																	<div class="col-xl-6">
																		<!--begin::Input-->
																		<div class="form-group">
																			<label>Password</label>
																			<input type="password" class="form-control form-control-lg" name="password" placeholder="Password" value="Password" />
																		</div>
																		<!--end::Input-->
																	</div>
																	<div class="col-xl-6">
																		<!--begin::Input-->
																		<div class="form-group">
																			<label>Areas to focus in Nutra</label>
																			<select name="focus" class="form-control form-control-lg">
																				<option value="">Select</option>
																				<option value="AF" selected="selected">Option 1</option>
																				<option value="AX">Option 2</option>
																				<option value="AL">Option 3</option>
																				<option value="DZ">Option 4</option>
																				<option value="AS">Option 5</option>
																				<option value="AD">Option 6</option>
																			</select>
																		</div>
																		<!--end::Input-->
																	</div>
																</div>
																<div class="row">
																	<div class="col-xl-6">
																		<!--begin::Input-->
																		<div class="form-group">
																			<label>Phone no.</label>
																			<input type="phone" class="form-control form-control-lg" name="phone" placeholder="Phone No" value="9967744431" />
																		</div>
																		<!--end::Input-->
																	</div>
																	<div class="col-xl-6">
																		<!--begin::Input-->
																		<div class="form-group">
																			<label>Types of Market access</label>
																			<select name="market" class="form-control form-control-lg">
																				<option value="">Select</option>
																				<option value="AF">Option 1</option>
																				<option value="AX">Option 2</option>
																				<option value="AL">Option 3</option>
																				<option value="DZ" selected="selected">Option 4</option>
																				<option value="AS">Option 5</option>
																				<option value="AD">Option 6</option>
																			</select>
																		</div>
																		<!--end::Input-->
																	</div>
																	<div class="col-xl-12">
																		<!--begin::Input-->
																		<div class="form-group">
																			<label>Address</label>
																			<input type="text" class="form-control form-control-lg" name="phone" placeholder="Address" value="A-21, Park Street, Bangalore- 709901" />
																		</div>
																		<!--end::Input-->
																	</div>
																</div>
																<hr>
																<div class="mt-10 mb-5 font-weight-bold text-dark lead">Company  Information</div>
																<div class="row">
																	<div class="col-xl-12">
																		<!--begin::Input-->
																		<div class="form-group">
																			<label for="factory-equipments">About your Company</label>
																			<textarea class="form-control form-control-lg" id="factory-equipments" rows="3"></textarea>
																		</div>
																		<!--end::Input-->
																	</div>
																</div>
																<div id="kt_repeater_2">
																	<div data-repeater-list="" class="row">
																		<div class="col-xl-6">
																			<div class="form-group">
																				<!--begin::Input-->
																				<label for="upload">Upload your company certifications here</label>
																				<div class="input-group mb-3">
																					<div class="custom-file">
																						<input type="file" class="custom-file-input form-control" id="upload01">
																						<label class="custom-file-label" for="upload01">Choose file</label>
																					</div>
																					<span class="form-text text-muted w-100">Maximum size: not more than 2mb</span>
																				</div>
																				<!--end::Input-->
																			</div>
																		</div>
																		<div data-repeater-item="" class="col-xl-6">
																			<div class="form-group">
																				<!--begin::Input-->
																				<label for="upload">Upload your company certifications here</label>
																				<div class="input-group mb-3">
																					<div class="custom-file">
																						<input type="file" class="custom-file-input form-control" id="upload01">
																						<label class="custom-file-label" for="upload01">Choose file</label>
																					</div>
																					<span class="form-text text-muted w-100">Maximum size: not more than 2mb</span>
																				</div>
																				<!--end::Input-->
																			</div>
																		</div>
																	</div>
																	<div class="form-group">
																		<div data-repeater-create="" class="btn btn-warning">
																			<i class="la la-plus"></i>Add more Certificates</div>
																	</div>
																</div>
																<div class="row">
																	<div class="col-xl-6">
																		<div class="form-group">
																			<label for="col-fdate">Date of Establishment</label>
																			<div class="input-group date" id="kt_datepicker_2" data-target-input="nearest">
																				<input type="text" class="form-control form-control-lg date" readonly="readonly" placeholder="Select date" />
																				<div class="input-group-append">
																					<span class="input-group-text">
																						<i class="ki ki-calendar"></i>
																					</span>
																				</div>
																			</div>																		
																		</div>
																		<!--end::Input-->
																	</div>
																	<div class="col-xl-6">
																		<!--begin::Input-->
																		<div class="form-group">
																			<label>Location</label>
																			<input type="text" class="form-control form-control-lg" name="password" placeholder="Location" value="Search" />
																		</div>
																		<!--end::Input-->
																	</div>
																</div>
																<div class="row">
																	<div class="col-xl-12 py-5 text-center">
																		<a href="#" class="btn btn-primary btn-lg">Save Changes</a>
																	</div>
																</div>
															</form>
														</div>
													</div>
													<!--end::Form-->
												</div>
											</div>
											<!--end::Card-->
											
										</div>
									</div>
								</div>
								<!--end::Container-->
							</div>
							<!--end::Entry-->
	
						</div>
						
					</div>
					{% endblock %}
				
				
				<!--end::Wrapper-->
		
		
		<!--begin::Scrolltop-->
		<div id="kt_scrolltop" class="scrolltop">
			<span class="svg-icon">
				<!--begin::Svg Icon | path:{% static 'assets/media/svg/icons/Navigation/Up-2.svg' %}-->
				<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
					<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
						<polygon points="0 0 24 0 24 24 0 24" />
						<rect fill="#000000" opacity="0.3" x="11" y="10" width="2" height="10" rx="1" />
						<path d="M6.70710678,12.7071068 C6.31658249,13.0976311 5.68341751,13.0976311 5.29289322,12.7071068 C4.90236893,12.3165825 4.90236893,11.6834175 5.29289322,11.2928932 L11.2928932,5.29289322 C11.6714722,4.91431428 12.2810586,4.90106866 12.6757246,5.26284586 L18.6757246,10.7628459 C19.0828436,11.1360383 19.1103465,11.7686056 18.7371541,12.1757246 C18.3639617,12.5828436 17.7313944,12.6103465 17.3242754,12.2371541 L12.0300757,7.38413782 L6.70710678,12.7071068 Z" fill="#000000" fill-rule="nonzero" />
					</g>
				</svg>
				<!--end::Svg Icon-->
			</span>
		</div>

		{% block scripts %}
		<!--begin::Page Scripts(used by this page)-->
		<script src="{% static 'assets/js/pages/crud/forms/widgets/bootstrap-datepicker.js' %}"></script>
		<script src="{% static 'assets/js/pages/crud/forms/widgets/form-repeater.js' %}"></script>
		{% endblock %}
	